import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import java.io.PrintWriter;
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.text.ParseException;
import javax.swing.event.ListSelectionListener;
import javax.swing.event.ListSelectionEvent;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JSpinner;
import javax.swing.Timer;





/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author lenovo
 */
public class FormCatatanHarian extends javax.swing.JFrame {
    
     //Model data catatan
    public class Catatan {
    String tanggal;
    String waktu;
    String isi;

    public Catatan(String tanggal, String waktu, String isi) {
        this.tanggal = tanggal;
        this.waktu = waktu;
        this.isi = isi;
    }

    @Override
    public String toString() {
        return tanggal + " " + waktu + " - " + isi;
    }
}


    // ===== ArrayList untuk menyimpan data =====
    ArrayList<Catatan> daftar = new ArrayList<>();


    /**
     * Creates new form FormCatatanHarian
     */
    //Constructor
    public FormCatatanHarian() {
        initComponents();
       
       // Spinner waktu: bergerak per menit (bukan jam) 
      spinnerWaktu.setModel(new javax.swing.SpinnerDateModel(
        new Date(),     
        null,              
        null,                
        java.util.Calendar.MINUTE 
));

JSpinner.DateEditor timeEditor = new JSpinner.DateEditor(spinnerWaktu, "HH:mm");
spinnerWaktu.setEditor(timeEditor);
    
     // Ketika item di list dipilih → tampilkan detail catatan
     listCatatan.addListSelectionListener(new ListSelectionListener() {
    @Override
    public void valueChanged(ListSelectionEvent e) {
        if (!e.getValueIsAdjusting()) {
            int i = listCatatan.getSelectedIndex();
            if (i >= 0 && i < daftar.size()) {

                Catatan c = daftar.get(i);

                try {
                    // === Tampilkan TANGGAL ===
                    SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
                    Date tgl = sdf.parse(c.tanggal);
                    dateChooserTanggal.setDate(tgl);

                    // === Tampilkan WAKTU ===
                    SimpleDateFormat tm = new SimpleDateFormat("HH:mm");
                    Date wkt = tm.parse(c.waktu);
                    spinnerWaktu.setValue(wkt);

                } catch (Exception ex) {
                    ex.printStackTrace();
                }

                // === Tampilkan ISI Catatan ===
                txtIsi.setText(c.isi);
            }
        }
    }
});
    }
    
    //Update waktu realtime ke label
    private void updateWaktu() {
    java.text.SimpleDateFormat sdf = new java.text.SimpleDateFormat("HH:mm:ss");
    lblWaktu.setText(sdf.format(new java.util.Date()));
}
    
    //Memperbarui tampilan daftar catatan
    private void refreshList() {
    DefaultListModel<String> model = new DefaultListModel<>();
    for (Catatan c : daftar) {
        model.addElement(c.toString());
    }
    listCatatan.setModel(model);
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblTanggal = new javax.swing.JLabel();
        lblIsi = new javax.swing.JLabel();
        scrollIsi = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtIsi = new javax.swing.JTextArea();
        lblList = new javax.swing.JLabel();
        scrollList = new javax.swing.JScrollPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        listCatatan = new javax.swing.JList<>();
        btnTambah = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnSimpan = new javax.swing.JButton();
        btnMuat = new javax.swing.JButton();
        spinnerWaktu = new javax.swing.JSpinner();
        lblWaktu = new javax.swing.JLabel();
        dateChooserTanggal = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(220, 236, 249));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(8, 76, 141));
        jLabel1.setText("Catatan Harian");

        lblTanggal.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTanggal.setForeground(new java.awt.Color(13, 59, 102));
        lblTanggal.setText("Tanggal:");

        lblIsi.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblIsi.setForeground(new java.awt.Color(13, 59, 102));
        lblIsi.setText("Isi Catatan:");

        scrollIsi.setBackground(new java.awt.Color(255, 255, 255));
        scrollIsi.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(169, 196, 224)));

        txtIsi.setColumns(20);
        txtIsi.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtIsi.setRows(5);
        jScrollPane1.setViewportView(txtIsi);

        scrollIsi.setViewportView(jScrollPane1);

        lblList.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblList.setForeground(new java.awt.Color(13, 59, 102));
        lblList.setText("Daftar Catatan:");

        listCatatan.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(169, 196, 224)));
        listCatatan.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jScrollPane2.setViewportView(listCatatan);

        scrollList.setViewportView(jScrollPane2);

        btnTambah.setBackground(new java.awt.Color(27, 152, 224));
        btnTambah.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnTambah.setForeground(new java.awt.Color(255, 255, 255));
        btnTambah.setText("Tambah");
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });

        btnEdit.setBackground(new java.awt.Color(27, 152, 224));
        btnEdit.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnEdit.setForeground(new java.awt.Color(255, 255, 255));
        btnEdit.setText("Edit");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnHapus.setBackground(new java.awt.Color(27, 152, 224));
        btnHapus.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnHapus.setForeground(new java.awt.Color(255, 255, 255));
        btnHapus.setText("Hapus");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        btnSimpan.setBackground(new java.awt.Color(27, 152, 224));
        btnSimpan.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSimpan.setForeground(new java.awt.Color(255, 255, 255));
        btnSimpan.setText("Simpan");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        btnMuat.setBackground(new java.awt.Color(27, 152, 224));
        btnMuat.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnMuat.setForeground(new java.awt.Color(255, 255, 255));
        btnMuat.setText("Muat");
        btnMuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMuatActionPerformed(evt);
            }
        });

        spinnerWaktu.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        lblWaktu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblWaktu.setForeground(new java.awt.Color(13, 59, 102));
        lblWaktu.setText("Waktu:");

        dateChooserTanggal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(169, 196, 224)));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(lblTanggal)
                        .addGap(18, 18, 18)
                        .addComponent(dateChooserTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(lblWaktu)
                        .addGap(18, 18, 18)
                        .addComponent(spinnerWaktu, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnTambah))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(lblIsi)
                        .addGap(18, 18, 18)
                        .addComponent(scrollIsi, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(lblList)
                        .addGap(18, 18, 18)
                        .addComponent(scrollList, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(161, 161, 161)
                        .addComponent(btnSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(btnMuat, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(207, 207, 207)
                        .addComponent(jLabel1)))
                .addGap(65, 65, 65))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel1)
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(lblTanggal))
                    .addComponent(dateChooserTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(lblWaktu))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(spinnerWaktu, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(lblIsi))
                    .addComponent(scrollIsi, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(btnEdit)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(lblList))
                    .addComponent(scrollList, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(btnHapus)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMuat)
                    .addComponent(btnSimpan))
                .addGap(6, 6, 6))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        // TODO add your handling code here:
    Date date = dateChooserTanggal.getDate();
    if (date == null) {
    JOptionPane.showMessageDialog(this, "Pilih tanggal terlebih dahulu!");
    return;
    }
    SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
    String tgl = sdf.format(date);


    // Ambil waktu dari spinner
    SimpleDateFormat timeFormat = new SimpleDateFormat("HH:mm");
    String waktu = timeFormat.format(spinnerWaktu.getValue());

    String isi = txtIsi.getText().trim();
    if (isi.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Isi semua field terlebih dahulu!");
        return;
    }
    // Simpan ke ArrayList
    daftar.add(new Catatan(tgl, waktu, isi));
    refreshList(); // Perbarui tampilan daftar catatan
    listCatatan.setSelectedIndex(listCatatan.getModel().getSize() - 1);
    dateChooserTanggal.setDate(null);
    txtIsi.setText(""); // Mengosongkan field isi
    }//GEN-LAST:event_btnTambahActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
    int i = listCatatan.getSelectedIndex();
    if (i < 0) {
        JOptionPane.showMessageDialog(this, "Pilih catatan yang ingin diedit.");
        return;
    }

    // Konfirmasi edit
    int confirm = JOptionPane.showConfirmDialog(this, 
            "Apakah Anda yakin ingin mengedit catatan ini?", 
            "Konfirmasi Edit", 
            JOptionPane.YES_NO_OPTION);

    if (confirm == JOptionPane.YES_OPTION) {
        Date date = dateChooserTanggal.getDate();
        if (date == null) {
            JOptionPane.showMessageDialog(this, "Pilih tanggal terlebih dahulu!");
            return;
        }

        // Format tanggal ke string
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        String tgl = sdf.format(date);

        // Ambil isi baru
        String isiBaru = txtIsi.getText().trim();
        if (isiBaru.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Isi catatan tidak boleh kosong.");
            return;
        }

        // Ambil waktu dari spinner
        SimpleDateFormat timeFormat = new SimpleDateFormat("HH:mm");
        String waktuBaru = timeFormat.format(spinnerWaktu.getValue());

        // Ganti catatan di daftar
        daftar.set(i, new Catatan(tgl, waktuBaru, isiBaru));

        // Refresh tampilan
        refreshList();
        listCatatan.setSelectedIndex(i);  // tetap memilih item yang diedit
    }
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // TODO add your handling code here:
     int i = listCatatan.getSelectedIndex();
    if (i < 0) {
        JOptionPane.showMessageDialog(this, "Pilih catatan yang ingin dihapus.");
        return;
    }

    int confirm = JOptionPane.showConfirmDialog(this, "Apakah Anda yakin ingin menghapus catatan ini?", "Konfirmasi Hapus", JOptionPane.YES_NO_OPTION);
    if (confirm == JOptionPane.YES_OPTION) {
        daftar.remove(i);
        refreshList();
    }
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        // TODO add your handling code here:
      javax.swing.JFileChooser chooser = new javax.swing.JFileChooser();
    chooser.setDialogTitle("Simpan sebagai...");
    
    int result = chooser.showSaveDialog(this);
    
    if (result == javax.swing.JFileChooser.APPROVE_OPTION) {
        java.io.File file = chooser.getSelectedFile();

        // Pastikan ekstensi .txt
        if (!file.getName().toLowerCase().endsWith(".txt")) {
            file = new java.io.File(file.getAbsolutePath() + ".txt");
        }

        try (PrintWriter out = new PrintWriter(file)) {
            for (Catatan c : daftar) {
                out.println(c.tanggal + "|" + c.waktu + "|" + c.isi.replace("\n", " "));
            }
            JOptionPane.showMessageDialog(this, 
                    "Data berhasil disimpan ke:\n" + file.getName());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal menyimpan file: " + e.getMessage());
        }
    }
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void btnMuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMuatActionPerformed
        // TODO add your handling code here:
     javax.swing.JFileChooser chooser = new javax.swing.JFileChooser();
    chooser.setDialogTitle("Pilih file TXT untuk dimuat");

    int result = chooser.showOpenDialog(this);

    if (result == javax.swing.JFileChooser.APPROVE_OPTION) {
        java.io.File file = chooser.getSelectedFile();

        daftar.clear();

        try (BufferedReader br = new BufferedReader(new FileReader(file))) {
            String line;
            while ((line = br.readLine()) != null) {
                String[] parts = line.split("\\|", 3);
                if (parts.length >= 3) {
                    daftar.add(new Catatan(parts[0], parts[1], parts[2]));
                }
            }
            refreshList();
            JOptionPane.showMessageDialog(this, 
                    "Data berhasil dimuat dari:\n" + file.getName());

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal membaca file: " + e.getMessage());
        }
    }
    }//GEN-LAST:event_btnMuatActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormCatatanHarian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormCatatanHarian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormCatatanHarian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormCatatanHarian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormCatatanHarian().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnMuat;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JButton btnTambah;
    private com.toedter.calendar.JDateChooser dateChooserTanggal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblIsi;
    private javax.swing.JLabel lblList;
    private javax.swing.JLabel lblTanggal;
    private javax.swing.JLabel lblWaktu;
    private javax.swing.JList<String> listCatatan;
    private javax.swing.JScrollPane scrollIsi;
    private javax.swing.JScrollPane scrollList;
    private javax.swing.JSpinner spinnerWaktu;
    private javax.swing.JTextArea txtIsi;
    // End of variables declaration//GEN-END:variables
}
